#!/bin/bash
# Run Prism Bonsai 2 27B (Ternary-Bonsai-2-27B-PQ2_0) with the ds4 engine.
#
# Usage:  ./run-bonsai.sh                 generate from the default prompt
#         ./run-bonsai.sh "a prompt"      generate from your prompt
#         ./run-bonsai.sh -n 32 "prompt"  greedy tokens to generate (default 24)
#         ./run-bonsai.sh --cpu "prompt"  run the CPU reference instead of the GPU
#         ./run-bonsai.sh compare [prompt]  both backends, diffed token for token
#         ./run-bonsai.sh session [prompt]  the CUDA session path, diffed against the reference
#         ./run-bonsai.sh bench [tokens]    decode rate (default 16 tokens)
#         ./run-bonsai.sh status            what is installed and what can run
#         ./run-bonsai.sh help
#
# This model is the "qwen35" family: a dense 64-layer trunk (48 gated
# delta-net layers and 16 gated-attention layers), every matmul weight PQ2_0
# (ternary, 2.125 bits per weight) and stored Hadamard-folded, so the engine
# rotates the activation instead of the weight.
#
# The entry is the diagnostic generator --first-token-test, which decodes
# greedily on the CUDA graph (--cuda) or on the built-in CPU reference
# (--cpu).  The CPU reference is the oracle the CUDA kernels are measured
# against, which is what "compare" proves: the same token ids from both
# backends.  "session" proves the same thing for the session path: with
# DS4_QWEN35_SESSION=1 the diagnostic drives the prompt and the greedy steps
# through a real ds4_session (create, sync, eval) and must print the identical
# ids.  Launching the binary without --first-token-test now runs the session
# path for real ("ds4 -m ... --cuda -p 'prompt' -n 24 -t 0" for greedy, the
# default temperature samples); the server path is a later unit and is not
# wired into this script yet.
#
# Env overrides: DS4_BONSAI_MODEL (model path), DS4_BONSAI_BIN (binary),
# DS4_BONSAI_BACKEND (cuda|cpu), DS4_BONSAI_STEPS (default tokens).

set -u

BIN="${DS4_BONSAI_BIN:-/data/ds4/ds4}"
MODEL="${DS4_BONSAI_MODEL:-/data/models/Ternary-Bonsai-2-27B-PQ2_0.gguf}"
BACKEND="${DS4_BONSAI_BACKEND:-cuda}"
STEPS="${DS4_BONSAI_STEPS:-24}"
DEFAULT_PROMPT="The capital of France is"
LOG="${DS4_BONSAI_LOG:-/tmp/bonsai-run.log}"

die() { echo "ERROR: $*" >&2; exit 1; }

check_env() {
  [ -x "$BIN" ] || die "ds4 binary not found or not executable at $BIN (build it: cd /data/ds4 && make ds4 CUDA_ARCH=native)"
  [ -f "$MODEL" ] || die "model not found: $MODEL"
  if [ "$BACKEND" = "cuda" ]; then
    command -v nvidia-smi >/dev/null || die "nvidia-smi not found; use --cpu or DS4_BONSAI_BACKEND=cpu"
    local busy
    busy=$(nvidia-smi --query-compute-apps=pid,process_name,used_memory --format=csv,noheader | head -3)
    if [ -n "$busy" ]; then
      echo "note: another process is using the GPU right now:"
      echo "$busy" | sed 's/^/      /'
      echo "      the 12 GB card is shared, so expect slower runs and possible OOM."
    fi
  fi
}

# Generated text from a log: the token lines carry the id and the raw text.
# A token whose text is a newline leaves an empty remainder on its own line, so
# an empty remainder is printed as a newline rather than dropped.
continuation() {
  awk '/^token /{sub(/^token [0-9]+: [0-9]+ /,""); if (length($0)==0) printf "\n"; else printf "%s", $0}' "$1"
}

# One decoding run: generate <prompt> <tokens> <backend> <log>
# Prints the backend, the wall time, the rate and the continuation.
generate() {
  local prompt="$1" steps="$2" backend="$3" log="$4"
  local t0 t1 wall rc
  t0=$(date +%s.%N)
  DS4_QWEN35_STEPS="$steps" "$BIN" -m "$MODEL" --"$backend" \
      --first-token-test --raw -p "$prompt" > "$log" 2>&1
  rc=$?
  t1=$(date +%s.%N)
  wall=$(awk -v a="$t0" -v b="$t1" 'BEGIN{printf "%.2f", b-a}')
  if [ "$rc" -ne 0 ]; then
    echo "run failed (exit $rc); last lines of $log:"
    tail -5 "$log"
    return 1
  fi
  echo "backend:      $backend"
  echo "wall:         ${wall}s for the prompt plus $steps greedy tokens (includes the model load)"
  printf 'decode rate:  %s tokens/s\n' \
    "$(awk -v w="$wall" -v n="$steps" 'BEGIN{if (w>0) printf "%.2f", n/w; else print "n/a"}')"
  echo "continuation:"
  printf '  %s\n' "$(continuation "$log")"
}

run_mode() {
  check_env
  echo "model:   $MODEL"
  echo "prompt:  $PROMPT"
  echo "steps:   $STEPS"
  echo "note:    one token per forward; there is no batched prefill yet"
  echo
  generate "$PROMPT" "$STEPS" "$BACKEND" "$LOG"
}

compare_mode() {
  check_env
  echo "model:   $MODEL"
  echo "prompt:  $PROMPT"
  echo "steps:   $STEPS, generated by both backends"
  echo
  echo "--- CUDA graph ---"
  generate "$PROMPT" "$STEPS" cuda "$LOG" || return 1
  grep -E '^token ' "$LOG" > /tmp/bonsai-cuda.tokens
  echo
  echo "--- CPU reference (the oracle) ---"
  generate "$PROMPT" "$STEPS" cpu "$LOG" || return 1
  grep -E '^token ' "$LOG" > /tmp/bonsai-cpu.tokens
  echo
  echo "--- token-for-token diff ---"
  if diff -q /tmp/bonsai-cpu.tokens /tmp/bonsai-cuda.tokens >/dev/null; then
    echo "IDENTICAL: all $STEPS generated token ids agree, so the CUDA graph"
    echo "           reproduces the CPU reference on this prompt"
    echo "           (per-backend token lines kept at /tmp/bonsai-{cpu,cuda}.tokens)"
  else
    echo "DIFFERENT - first differences (cpu vs cuda):"
    diff /tmp/bonsai-cpu.tokens /tmp/bonsai-cuda.tokens | head -20
    return 1
  fi
}

bench_mode() {
  check_env
  local n="$1"
  echo "model:   $MODEL"
  echo "tokens:  $n greedy, one forward each, after the prompt"
  echo
  generate "$DEFAULT_PROMPT" "$n" "$BACKEND" "$LOG"
}

# The session path on the CUDA graph, diffed against the CPU reference: the
# same prompt and the same greedy steps, driven through ds4_session instead of
# the diagnostic's local graph, so the token ids must match exactly.
session_mode() {
  check_env
  echo "model:   $MODEL"
  echo "prompt:  $PROMPT"
  echo "steps:   $STEPS, generated through the session path and the reference"
  echo
  echo "--- CUDA session (create, sync, eval) ---"
  local t0 t1 wall rc
  t0=$(date +%s.%N)
  DS4_QWEN35_SESSION=1 DS4_QWEN35_STEPS="$STEPS" "$BIN" -m "$MODEL" --cuda \
      --first-token-test --raw -p "$PROMPT" > "$LOG" 2>&1
  rc=$?
  t1=$(date +%s.%N)
  wall=$(awk -v a="$t0" -v b="$t1" 'BEGIN{printf "%.2f", b-a}')
  if [ "$rc" -ne 0 ]; then
    echo "session run failed (exit $rc); last lines of $LOG:"
    tail -5 "$LOG"
    return 1
  fi
  echo "backend:      cuda (session)"
  echo "wall:         ${wall}s for the prompt plus $STEPS greedy tokens"
  echo "continuation:"
  printf '  %s\n' "$(continuation "$LOG")"
  grep -E '^token ' "$LOG" > /tmp/bonsai-session.tokens
  echo
  echo "--- CPU reference (the oracle) ---"
  generate "$PROMPT" "$STEPS" cpu "$LOG" || return 1
  grep -E '^token ' "$LOG" > /tmp/bonsai-cpu.tokens
  echo
  echo "--- token-for-token diff ---"
  if diff -q /tmp/bonsai-cpu.tokens /tmp/bonsai-session.tokens >/dev/null; then
    echo "IDENTICAL: all $STEPS generated token ids agree, so the session path"
    echo "           reproduces the CPU reference on this prompt"
    echo "           (per-path token lines kept at /tmp/bonsai-{cpu,session}.tokens)"
  else
    echo "DIFFERENT - first differences (cpu vs session):"
    diff /tmp/bonsai-cpu.tokens /tmp/bonsai-session.tokens | head -20
    return 1
  fi
}

status_mode() {
  echo "binary:  $BIN"
  if [ -x "$BIN" ]; then
    echo "         present, built $(stat -c '%y' "$BIN" | cut -d. -f1)"
  else
    echo "         MISSING or not executable"
  fi
  echo "model:   $MODEL"
  if [ -f "$MODEL" ]; then
    echo "         present, $(stat -c '%s' "$MODEL" | awk '{printf "%.2f GiB", $1/1073741824}')"
  else
    echo "         MISSING"
  fi
  if command -v nvidia-smi >/dev/null; then
    echo "gpu:     $(nvidia-smi --query-gpu=name,memory.used,memory.total --format=csv,noheader)"
    local busy
    busy=$(nvidia-smi --query-compute-apps=pid,process_name,used_memory --format=csv,noheader | head -3)
    if [ -n "$busy" ]; then
      echo "         in use by another process:"
      echo "$busy" | sed 's/^/           /'
    else
      echo "         no compute process"
    fi
  else
    echo "gpu:     nvidia-smi not found (the CUDA graph needs it)"
  fi
  if [ -x "$BIN" ] && [ -f "$MODEL" ]; then
    echo "model:   $("$BIN" -m "$MODEL" --inspect 2>/dev/null | grep -E '^arch|logical parameters' | tr '\n' ' ')"
  fi
  echo "entry:   --first-token-test (greedy diagnostic) and the plain CLI"
  echo "         generation, which now runs the CUDA session path; the server"
  echo "         path is a later unit and is not wired into this script yet."
}

usage() {
  sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'
}

# --- argument parsing -------------------------------------------------------
PROMPT="$DEFAULT_PROMPT"
case "${1:-}" in
  compare)        shift; [ $# -gt 0 ] && PROMPT="$*"; compare_mode ;;
  session)        shift; [ $# -gt 0 ] && PROMPT="$*"; session_mode ;;
  bench)          shift; bench_mode "${1:-16}" ;;
  status)         status_mode ;;
  help|-h|--help) usage ;;
  --cpu)          shift; BACKEND=cpu; [ $# -gt 0 ] && PROMPT="$*"; run_mode ;;
  -n)             shift; STEPS="${1:-24}"; shift || true; [ $# -gt 0 ] && PROMPT="$*"; run_mode ;;
  "")             run_mode ;;
  *)              PROMPT="$*"; run_mode ;;
esac
